# Generated by Django 5.0.4 on 2024-08-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplemento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suplemento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='suplemento',
            name='descricao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='suplemento',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='suplemento',
            name='marca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='suplemento',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
