# Generated by Django 5.0.4 on 2024-08-31 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suplemento', '0002_remove_suplemento_tipo_suplemento_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suplemento',
            name='data_validade',
        ),
    ]
