# Generated by Django 5.0.4 on 2024-09-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('M', 'Matriculado'), ('NM', 'Não Matriculado')], default='M', max_length=2),
        ),
    ]
