# Generated by Django 5.0.4 on 2024-09-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_alter_aluno_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='plano',
        ),
    ]
