# Generated by Django 5.0.4 on 2024-08-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
